import {createStore} from 'vuex'

export const store = createStore({
    state: {
        //所有游戏
        gameList: [
            {
                id: 2,
                name: '赛博朋克2077',
                enName: 'Cyberpunk 2077',
                covers: ['/2077/2077.jpg', '/2077/1-1.jpg', '/2077/1-2.jpg', '/2077/1-3.jpg', '/2077/1-4.jpg'],
                tag: ['单人', '大师级', '开放世界', '赛博朋克'],
                originalPrice: 298,
                nowPrice: 149,
                score: 6.5,
                scoreNum: 13045,
                intro: '《赛博朋克 2077》的故事发生在夜之城，权力更迭和身体改造是这里不变的主题。玩家将扮演一名野心勃勃的雇佣兵：V，追寻一种独一无二的植入体——获得永生的关键。自定义角色义体、技能和玩法，探索包罗万象的城市。玩家做出的选择也将会对剧情和周遭世界产生影响。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 4,
                achievements: 127,
                avgTime: 100
            },
            {
                id: 4,
                name: '侠盗猎车手：罪恶都市',
                enName: 'Grand Theft Auto：Vice City',
                covers: ['/gta5/gta5.jpg', '/gta5/6-1.jpg', '/gta5/6-2.jpg', '/gta5/6-3.jpg', '/gta5/6-4.jpg', '/gta5/6-5.jpg'],
                tag: ['多人', '开放世界', '大师级'],
                originalPrice: 119,
                nowPrice: 59,
                score: 9.6,
                scoreNum: 65821,
                intro: '《侠盗猎车手》在黑帮的背景下混合了驾驶、枪战、格斗、养成乃至经营的元素。这款游戏自《侠盗猎车手：罪恶都市》发行以后便迅速占领玩家们的视野，大多数中国玩家从这里开始认识《侠盗猎车手》。',
                recommend: true,
                recomReason: '好友最近在玩',
                salesVolume: 2,
                achievements: 159,
                avgTime: 230
            },
            {
                id: 8,
                name: '文明6',
                enName: 'Sid Meier’s Civilization VI',
                covers: ['/Civilization6/Civilization6.jpg', '/Civilization6/3-1.jpg', '/Civilization6/3-2.jpg', '/Civilization6/3-3.jpg', '/Civilization6/3-4.jpg', '/Civilization6/3-5.jpg'],
                tag: ['多人', '策略', '大战略', '回合战略'],
                originalPrice: 199,
                nowPrice: 29,
                score: 9.4,
                scoreNum: 12198,
                intro: '游戏中玩家建立起一个帝国，并接受时间的考验。玩家将创建及带领自己的文明从石器时代迈向信息时代，并成为世界的领导者。在尝试建立起世界上赫赫有名的伟大文明的过程中，玩家将启动战争、实行外交、促进文化，同时正面对抗历史上的众多领袖。',
                recommend: true,
                recomReason: '玩过相似',
                salesVolume: 6,
                achievements: 89,
                avgTime: 240
            },
            {
                id: 9,
                name: '战地风云2042',
                enName: 'Battlefield 2042',
                covers: ['/2042/2042.jpg', '/2042/0-1.jpg', '/2042/0-2.jpg', '/2042/0-3.jpg', '/2042/0-4.jpg'],
                tag: ['多人', '动作', '第一人称射击', '狗都不玩'],
                originalPrice: 248,
                nowPrice: 112,
                score: 5.1,
                scoreNum: 3483,
                intro: '《战地风云 2042》是《战地风云》系列的全新续作，并非是《战地6》，游戏的主体框架为《战地2142》的前传，也是《战地风云》（在国内简称为《战地》）系列的正统续作，游戏背景设定为近未来（公元2042年），会有动态的天气系统，以及改善后的破坏系统。本作为《战地风云》系列首次支持 128 名玩家同时加入全面战争——让玩家有机会参与大规模战斗。',
                recommend: true,
                recomReason: '大家都在玩',
                salesVolume: 7,
                achievements: 84,
                avgTime: 90
            },
            {
                id: 10,
                name: '荒野大镖客：救赎',
                enName: 'Red Dead Redemption',
                covers: ['/RDR2/RDR2.jpg', '/RDR2/9-1.jpg', '/RDR2/9-2.jpg', '/RDR2/9-3.jpg', '/RDR2/9-4.jpg', '/RDR2/9-5.jpg'],
                tag: ['剧情丰富', '冒险', '西部', '开放世界'],
                originalPrice: 249,
                nowPrice: 125,
                score: 9.4,
                scoreNum: 17587,
                intro: '游戏中述说前罪犯约翰·马斯顿因联邦探员以其家人性命相要挟，而被迫前往美国边境协助执法的故事',
                recommend: true,
                recomReason: '好友中热门',
                salesVolume: 5,
                achievements: 122,
                avgTime: 100
            },
            {
                id: 5,
                name: '彩虹六号：围攻',
                enName: 'Tom Clancy’s Rainbow Six Siege',
                covers: ['/rainbow6/rainbow6.jpg', '/rainbow6/8-1.jpg', '/rainbow6/8-2.jpg', '/rainbow6/8-3.jpg', '/rainbow6/8-4.jpg', '/rainbow6/8-5.jpg'],
                tag: ['恐怖', '多人', '第一人称射击', '战术'],
                originalPrice: 88,
                nowPrice: 19,
                score: 9.3,
                scoreNum: 39254,
                intro: '该作灵感来源于现实世界中的反恐行动，玩家将在游戏中将扮演警察或匪徒进行殊死较量。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 3,
                achievements: 69,
                avgTime: 250
            },
            {
                id: 6,
                name: '绝地求生',
                enName: 'PLAYERUNKNOWN’S BATTLEGROUNDS',
                covers: ['/pubg/pubg.jpg', '/pubg/7-1.jpg', '/pubg/7-2.jpg', '/pubg/7-3.jpg', '/pubg/7-4.jpg'],
                tag: ['生存', '多人', '第三人称射击', '大逃杀'],
                originalPrice: 98,
                nowPrice: 0,
                score: 6.5,
                scoreNum: 134568,
                intro: '在该游戏中，玩家需要在游戏地图上收集各种资源，并在不断缩小的安全区域内对抗其他玩家，让自己生存到最后。',
                recommend: true,
                recomReason: '免费游戏',
                salesVolume: 1,
                achievements: 57,
                avgTime: 300
            },
            {
                id: 3,
                name: '刺客信条：大革命',
                enName: 'Assassin‘s Creed Odyssey',
                covers: ['/cike/unity.jpg', '/cike/2-1.jpg', '/cike/2-2.jpg', '/cike/2-3.jpg', '/cike/2-4.jpg', '/cike/2-5.jpg'],
                tag: ['单人', '角色扮演', '开放世界', '暗杀'],
                originalPrice: 298,
                nowPrice: 59.6,
                score: 9.1,
                scoreNum: 13325,
                intro: '游戏设定于距《刺客信条：起源》故事发生前四百年的公元前431年，讲述了古希腊城邦之间的伯罗奔尼撒战争的秘密虚构历史。玩家扮演一名雇佣兵，可加入以雅典为首的提洛同盟或以斯巴达为首的伯罗奔尼撒同盟。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 10,
                achievements: 43,
                avgTime: 70
            },
            {
                id: 7,
                name: '艾尔登法环',
                enName: 'ELDEN RING',
                covers: ['/elden/elden.jpg', '/elden/5-1.jpg', '/elden/5-2.jpg', '/elden/5-3.jpg', '/elden/5-4.jpg', '/elden/5-5.jpg'],
                tag: ['类魂系列', 'ARPG', '黑暗奇幻', '开放世界'],
                originalPrice: 298,
                nowPrice: 298,
                score: 9.4,
                scoreNum: 15456,
                intro: '该游戏让玩家走进辽阔的场景与地下迷宫探索未知，挑战困难重重的险境，同时体验登场角色之间的利害关系谱成的群像剧。',
                recommend: true,
                recomReason: '商城上新',
                salesVolume: 4,
                achievements: 114,
                avgTime: 100
            },
            {
                id: 1,
                name: '求生之路2',
                enName: 'Left 4 Dead 2',
                covers: ['/left 4 dead 2/left 4.jpg', '1.jpg', '2.jpg', '3.jpg', '4.jpg'],
                tag: ['合作', '多人', '僵尸', '第一人称射击'],
                originalPrice: 37,
                nowPrice: 10,
                score: 9.6,
                scoreNum: 1289,
                intro: '游戏故事发生的时间与原作几乎相同，将呈现另外四名幸存者在僵尸横行的四个场景中奋力求生的艰辛历程，地点及时间背景与当前的L4D一致，只不过角色是新角色，场景是同一地点的另一位面，敌人中也将出现新的僵尸，新的近战武器，新的对抗僵尸武器和电锯。',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 9,
                achievements: 32,
                avgTime: 60
            },
            {
                id: 11,
                name: '喋血复仇',
                enName: 'back 4 blood',
                covers: ['/back4/back4.jpg', '/back4/1.jpg', '/back4/2.jpg', '/back4/3.jpg', '/back4/4.jpg'],
                tag: ['合作', '多人', '僵尸'],
                originalPrice: 298,
                nowPrice: 117.89,
                score: 6.6,
                scoreNum: 640,
                intro: '《喋血复仇》由备受好评的《求生之路》系列创作者打造，是一款惊险刺激的合作第一人称射击游戏。无论是体验激烈的4人合作叙事战役，还是扮演人类或灾变者进行竞争的多人游戏，丰富而多变的游戏内容总会让你杀个过瘾。',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 19,
                achievements: 28,
                avgTime: 40
            },
            {
                id: 12,
                name: '永劫无间',
                enName: 'Naraka: Bladepoint',
                covers: ['/naraka/naraka.jpg', '/naraka/1.jpg', '/naraka/2.jpg', '/naraka/3.jpg', '/naraka/4.jpg'],
                tag: ['大逃杀', '多人', '武术','玩家对战'],
                originalPrice: 98,
                nowPrice: 49,
                score: 6.4,
                scoreNum: 8979,
                intro: '游戏讲述了以虚构的幻想世界为背景，阴阳二神互相杀伐，导致世界处于永劫之中。玩家需扮演一名英雄，在地图中收集各种资源，与其他玩家对抗，生存到最后。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 18,
                achievements: 40,
                avgTime: 50
            },
            {
                id: 13,
                name: '极品飞车21：热度',
                enName: 'Need For Speed™:Heat',
                covers: ['/speed/need of speed.jpg', '/speed/1.jpg', '/speed/2.jpg', '/speed/3.jpg', '/speed/4.jpg'],
                tag: ['驾驶', '多人', '竞速','开放世界'],
                originalPrice: 288,
                nowPrice: 14.4,
                score: 8.1,
                scoreNum: 1721,
                intro: '游戏中玩家将进入以迈阿密为灵感来源的棕榈市、白天参加正式比赛、入夜后体验警匪追逐，在警官、街头赛车等多方势力之中参与整个故事。',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 17,
                achievements: 15,
                avgTime: 8
            },
            {
                id: 14,
                name: 'FIFA23',
                enName: 'FIFA23',
                covers: ['/fifa23/fifa.jpg', '/fifa23/1.jpg', '/fifa23/2.jpg', '/fifa23/3.jpg', '/fifa23/4.jpg'],
                tag: ['体育', '足球', '沉浸式','美式足球'],
                originalPrice: 248,
                nowPrice: 245.27,
                score: 4.8,
                scoreNum: 246,
                intro: '2022年8月12日，EA官方发布了《FIFA23》终极球队模式相关演示以及特点介绍，其中球队球员间化学反应系统大改，编队更加灵活，FUT Moments丰富单人游戏模式允许玩家复刻足球界的伟大时刻等',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 16,
                achievements: 32,
                avgTime: 10
            },
            {
                id: 15,
                name: '底特律：化身为人',
                enName: 'Detroit: Become Human',
                covers: ['/detroit/detroit.jpg', '/detroit/1.jpg', '/detroit/2.jpg', '/detroit/3.jpg', '/detroit/4.jpg'],
                tag: ['电影式', '选择取向', '剧情丰富','多结局'],
                originalPrice: 125,
                nowPrice: 63.3,
                score: 9.4,
                scoreNum: 3073,
                intro: '游戏的背景设定在2038年的虚拟底特律城，玩家将根据章节分别扮演三位主角卡拉、康纳、马库斯，在不同的选择中决定游戏结局。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 15,
                achievements: 23,
                avgTime: 18
            },
            {
                id:16 ,
                name: 'Wallpaper Engine',
                enName: 'Wallpaper Engine',
                covers: ['/wallpaper/wallpaper.jpg', '/wallpaper/1.jpg', '/wallpaper/2.jpg', '/wallpaper/3.jpg', '/wallpaper/4.jpg'],
                tag: ['软件', '漫画', '设计与插图','实用工具'],
                originalPrice: 19,
                nowPrice: 18.79,
                score: 9.8,
                scoreNum: 51268,
                intro: '支持各种类型的壁纸，包括2D和3D动画，网站，视频，甚至某些应用程序。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 14,
                achievements: 60,
                avgTime: 70
            },
            {
                id:17 ,
                name: '禁闭求生',
                enName: 'Grounded',
                covers: ['/grounded/grounded.jpg', '/grounded/1.jpg', '/grounded/2.jpg', '/grounded/3.jpg', '/grounded/4.jpg'],
                tag: ['大逃杀', '多人', '武术','玩家对战'],
                originalPrice: 119,
                nowPrice: 50,
                score: 8.3,
                scoreNum: 412,
                intro: '《禁闭求生》一款以生存为主题的第一人称生存冒险游戏，玩家在游戏中扮演被缩小成蚂蚁般大小的少年少女，置身表面看似平静、底层实则凶险的野外环境。为了在这个微小昆虫也能构成巨大威胁的环境中生存下去，众人必须齐心协力，运用收集到的材料来制作装备与建筑设施，对抗昆虫威胁，找到回家的路。游戏支持最多4人合作玩法，玩家将随着故事任务来探索这个复杂又丰富的游戏世界。',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 13,
                achievements: 28,
                avgTime: 9
            },
            {
                id:18 ,
                name: '人类一败涂地',
                enName: 'Human: Fall Flat',
                covers: ['/human/human.jpg', '/human/1.jpg', '/human/2.jpg', '/human/3.jpg', '/human/4.jpg'],
                tag: ['解密', '多人', '冒险','欢乐'],
                originalPrice: 58,
                nowPrice: 17.4,
                score: 9.4,
                scoreNum: 23568,
                intro: '《人类一败涂地》是一款轻松搞笑的沙雕游戏，游戏的场景发生在飘渺的梦境之中。他并不是让玩家安放各种机关让小人触发，而是操作身处梦境中的主角bob，利用物理效果解开梦中的各种谜题，比如荡秋千、撬开铁栅栏等等，最终逃出梦境。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 12,
                achievements: 36,
                avgTime: 21
            },
            {
                id:19 ,
                name: '真人快打11',
                enName: 'Mortal Kombat 11',
                covers: ['/mortal2/mortal.jpg', '/mortal2/1.jpg', '/mortal2/2.jpg', '/mortal2/3.jpg', '/mortal2/4.jpg'],
                tag: ['血腥', '格斗', '武术','成人'],
                originalPrice: 138,
                nowPrice: 28,
                score: 9.2,
                scoreNum: 876,
                intro: '《真人快打11》的剧情模式汇集了很多B级片的元素，除了足够血腥暴力之外，还非常的无厘头。把控剧情导向的主要因素是爽快，而不是严谨的逻辑。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 11,
                achievements: 28,
                avgTime: 32
            },
            {
                id:20 ,
                name: '中土世界：战争之影',
                enName: 'Middle-earth: Shadow of War',
                covers: ['/middle-earth/middle.jpg', '/middle-earth/1.jpg', '/middle-earth/2.jpg', '/middle-earth/3.jpg', '/middle-earth/4.jpg'],
                tag: ['动作', '开放世界', '角色扮演','奇幻'],
                originalPrice: 143,
                nowPrice: 21,
                score: 9.1,
                scoreNum: 4404,
                intro: '在游戏中，玩家需要深入敌后，组建军队，攻破要塞，从内部统治魔多。体验宿敌系统打造出的独一无二的个性剧情，正面对抗强大无比的黑暗魔君索伦和他的戒灵。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 20,
                achievements: 32,
                avgTime: 20
            },
            {
                id:21,
                name: '漫漫长夜',
                enName: 'The Long Dark',
                covers: ['/longdark/longdark.jpg', '/longdark/1.jpg', '/longdark/2.jpg', '/longdark/3.jpg', '/longdark/4.jpg'],
                tag: ['生存', '开放世界', '探索','单人'],
                originalPrice: 103,
                nowPrice: 20,
                score: 9.3,
                scoreNum: 2872,
                intro: '《漫漫长夜》拥有三个模式，剧情模式，沙盒模式(即生存模式)，和挑战模式。玩家在完成指定目标的同时还需时时监控自己的生命体征，包括卡路里，体温，疲劳，负重，饥饿和干渴。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 29,
                achievements: 35,
                avgTime: 20
            },
            {
                id:22,
                name: '黎明杀机',
                enName: 'Dead by Daylight',
                covers: ['/daylight/daylight.jpg', '/daylight/1.jpg', '/daylight/2.jpg', '/daylight/3.jpg', '/daylight/4.jpg'],
                tag: ['在线合作', '生存恐怖', '多人','恐怖'],
                originalPrice: 82,
                nowPrice: 32,
                score: 8.9,
                scoreNum: 8344,
                intro: '游戏扮演杀手的玩家视角为第一人称视角，拥有强大的能力，还可以使用特殊能力来追踪逃亡者。而扮演逃亡者的四名玩家则是第三人称视角，可以更好地观察周遭环境。玩家必须在强大的压力下做出残酷而正确的决定。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 28,
                achievements: 30,
                avgTime: 40
            },
            {
                id:23,
                name: '饥荒：联机版',
                enName: 'Don’t Starve Together',
                covers: ['/starve/starve.jpg', '/starve/1.jpg', '/starve/2.jpg', '/starve/3.jpg', '/starve/4.jpg'],
                tag: ['沙盒', '探索', '多人','在线合作'],
                originalPrice: 24,
                nowPrice: 9,
                score: 9.5,
                scoreNum: 14987,
                intro: '玩家将和同伴在没有任何指引和教程的情况下进入这个世界，克服不利环境和怪物袭击生存下去，而时间、饥饿和理智似乎总是对玩家不利。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 27,
                achievements: 60,
                avgTime: 100
            },
            {
                id:24,
                name: '人间地狱',
                enName: 'Hell Let Loose',
                covers: ['/hell let loose/hell.jpg', '/hell let loose/1.jpg', '/hell let loose/2.jpg', '/hell let loose/3.jpg', '/hell let loose/4.jpg'],
                tag: ['射击', '动作', '二战','第一人称射击'],
                originalPrice: 149,
                nowPrice: 67,
                score: 8.5,
                scoreNum: 866,
                intro: '人间地狱是让您置身于真实比例的第二次世界大战的标志性战场。在庞大的战场地图体验50对50的多人对抗游戏。在步兵、侦察、装甲单位等12个单位类型中选择一个，每个角色装备不同的武器、车辆和装备。扮演一名军官、侦察兵、机枪手、军医、工程师、坦克指挥官以及更多的角色。',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 26,
                achievements: 24,
                avgTime: 30
            },
            {
                id:25,
                name: '无主之地3',
                enName: 'Borderlands 3',
                covers: ['/borderlands3/borderlands3.jpg', '/borderlands3/1.jpg', '/borderlands3/2.jpg', '/borderlands3/3.jpg', '/borderlands3/4.jpg'],
                tag: ['动作', '寻宝', '角色扮演','刷宝射击游戏'],
                originalPrice: 199,
                nowPrice: 49.75,
                score: 8.6,
                scoreNum: 2976,
                intro: '在游戏中，玩家将选择四名全新寻宝猎人的其中一位，在全新的世界中和新型敌人展开殊死之战。与疯狂的敌人作战夺取成堆的战利品，并从星系最为残忍的邪教领袖手中拯救家园。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 25,
                achievements: 24,
                avgTime: 60
            },
            {
                id:26,
                name: '泰拉瑞亚',
                enName: 'Terraria',
                covers: ['/terraria/terraria.jpg', '/terraria/1.jpg', '/terraria/2.jpg', '/terraria/3.jpg', '/terraria/4.jpg'],
                tag: ['2D', '多人', '生存','沙盒'],
                originalPrice: 36,
                nowPrice: 12,
                score: 9.8,
                scoreNum: 11298,
                intro: '玩家可以在游戏中做很多事情：制造武器战胜各种各样的敌人及群落；挖掘地下寻找器材配件、金钱和其他有用的东西；收集木材，石材，矿石等资源；用世界里的一切创造你需要的东西并守护它。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 24,
                achievements: 18,
                avgTime: 10
            },
            {
                id:27,
                name: '漫威蜘蛛侠：重制版',
                enName: 'Marvel’s Spider-Man Remastered',
                covers: ['/spiderman/spiderman.jpg', '/spiderman/1.jpg', '/spiderman/2.jpg', '/spiderman/3.jpg', '/spiderman/4.jpg'],
                tag: ['超级英雄', '动作', '多人','开放世界'],
                originalPrice: 379,
                nowPrice: 379,
                score: 8.8,
                scoreNum: 871,
                intro: '《漫威蜘蛛侠》公布了新演示，蜘蛛侠运用其标志性的蛛丝技能在都市林立的高楼大厦间穿梭移动。本作于2018年9月7日正式发售，为PS4平台独占。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 23,
                achievements: 24,
                avgTime: 60
            },
            {
                id:28,
                name: '双人成行',
                enName: 'It Takes Two',
                covers: ['/takes two/takes.jpg', '/takes two/1.jpg', '/takes two/2.jpg', '/takes two/3.jpg', '/takes two/4.jpg'],
                tag: ['2D', '多人', '生存','沙盒'],
                originalPrice: 198,
                nowPrice: 79,
                score: 9.7,
                scoreNum: 7595,
                intro: '游戏需要2名玩家一同进行冒险，玩家在游戏中将扮演相互看不顺眼、被魔咒变成了玩偶的科迪和小梅夫妇。他们一起被困在一个奇幻世界里，每个角落都隐藏着意想不到的东西，他们不得不一起克服挑战，同时挽救他们破裂的关系。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 38,
                avgTime: 72
            },
            {
                id:29,
                name: 'NBA 2K23',
                enName: 'NBA 2K23',
                covers: ['/nba 2k23/nba.jpg', '/nba 2k23/1.jpg', '/nba 2k23/2.jpg', '/nba 2k23/3.jpg', '/nba 2k23/4.jpg'],
                tag: ['体育', '篮球', '模拟','沉浸式模拟'],
                originalPrice: 199,
                nowPrice: 199,
                score:5.4,
                scoreNum: 219,
                intro: '2022年7月30日，《NBA 2K23》官方公布了该作首部实机演示，预告中有如德文·布克、库里、浓眉、东契奇与詹姆斯等多位球星登场，以及女篮也在该演示中登场。',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 21,
                achievements: 18,
                avgTime: 5
            },
            {
                id:30,
                name: '泰坦陨落2',
                enName: 'Titanfall® 2',
                covers: ['/titanfall2/titanfall.jpg', '/titanfall2/1.jpg', '/titanfall2/2.jpg', '/titanfall2/3.jpg', '/titanfall2/4.jpg'],
                tag: ['多人', '射击', '机甲','玩家对战'],
                originalPrice: 158,
                nowPrice: 25,
                score:9.6,
                scoreNum: 9022,
                intro: '跃升起始包内含所有数字豪华版内容，让您快速升级和解锁物品，还有 R-201 卡宾枪的地下定制武器皮肤。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 20,
                achievements: 100,
                avgTime: 20
            },
            {
                id:31,
                name: '戴森球计划',
                enName: 'Dyson Sphere Program',
                covers: ['/dyson/dyson.jpg', '/dyson/1.jpg', '/dyson/2.jpg', '/dyson/3.jpg', '/dyson/4.jpg'],
                tag: ['基地建设', '建造', '自动化','太空'],
                originalPrice: 70,
                nowPrice: 56,
                score:9.7,
                scoreNum: 1949,
                intro: '浩瀚无垠的宇宙，未知的征程，作为戴森球计划的一名工程师，你将前往陌生的星系，建造戴森球。从一无所有白手起家，采集资源，规划设计生产线，逐步实现全自动化，将你的工厂从一个小作坊，发展成为庞大的跨星系工业帝国。探索未知的星球，发现珍奇，让你的足迹遍布星辰大海。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 39,
                achievements: 60,
                avgTime: 50
            },
            {
                id:32,
                name: '空洞骑士',
                enName: 'Hollow Knight',
                covers: ['/hollow/hollow.jpg', '/hollow/1.jpg', '/hollow/2.jpg', '/hollow/3.jpg', '/hollow/4.jpg'],
                tag: ['单人', '困难', '类魂游戏','平台游戏'],
                originalPrice: 48,
                nowPrice: 19,
                score:5.4,
                scoreNum: 219,
                intro: '在《空洞骑士》中打造属于自己的冒险之旅！穿越一个庞大却废弃的属于昆虫与英雄的王国，开启史诗般的冒险旅程。探索幽深的洞穴，与被感染的生物战斗，结识友好又奇异的昆虫，整个游戏都是经典的手绘 2D 风格。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 38,
                achievements: 70,
                avgTime: 10
            },
            {
                id:33,
                name: '森林',
                enName: 'The Forest',
                covers: ['/forest/forest.jpg', '/forest/1.jpg', '/forest/2.jpg', '/forest/3.jpg', '/forest/4.jpg'],
                tag: ['生存', '开放世界', '恐怖','建造'],
                originalPrice: 70,
                nowPrice: 18,
                score:9.3,
                scoreNum: 12654,
                intro: '作为客机坠毁的唯一幸存者，你发现自己身处一个神秘的森林中，与一个食人族变种人的社会作斗争，以求生存。建立，探索，生存在这个可怕的第一人称生存恐怖模拟器。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 37,
                achievements: 64,
                avgTime: 50
            },
            {
                id:34,
                name: '方舟：生存进化',
                enName: 'ARK: Survival Evolved',
                covers: ['/ark/ark.jpg', '/ark/1.jpg', '/ark/2.jpg', '/ark/3.jpg', '/ark/4.jpg'],
                tag: ['开放世界', '多人', '恐龙','基地建设'],
                originalPrice: 70,
                nowPrice: 23,
                score:8.8,
                scoreNum: 7584,
                intro: '由虚幻4引擎打造的一款多人在线生存竞技网游，在一个超高自由度的开放世界里，可以体验采集、制造、打猎、收获、建造、研究以及驯服恐龙等超多自由内容，感受酷热白昼、冰冷夜晚的动态天气系统以及饥饿口渴等现实中的生存挑战，还要面对其它生存者的威胁，合作生存还是竞技厮杀，由你决定！',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 36,
                achievements: 200,
                avgTime: 30
            },
            {
                id:35,
                name: '我们之间',
                enName: 'Among Us',
                covers: ['/amongus/amongus.jpg', '/amongus/1.jpg', '/amongus/2.jpg', '/amongus/3.jpg', '/amongus/4.jpg'],
                tag: ['独立', '动作', '斩杀','神话'],
                originalPrice: 22,
                nowPrice: 5,
                score:8.3,
                scoreNum: 1437,
                intro: '这是一款可以连线或本地游玩的派对游戏，4 到 15 名玩家相互合作与背叛... 一切都发生在太空之中！',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 21,
                achievements: 18,
                avgTime: 5
            },
            {
                id:36,
                name: '哈迪斯',
                enName: 'hades',
                covers: ['/hades/hades.jpg', '/hades/1.jpg', '/hades/2.jpg', '/hades/3.jpg', '/hades/4.jpg'],
                tag: ['单人', '角色扮演', '动作','神话'],
                originalPrice: 79,
                nowPrice: 48,
                score:9.5,
                scoreNum: 4283,
                intro: '挑战死神，在地狱中杀出血路。由 Bastion、Transistor 和 Pyre 原班人马打造的全新地下城 类游 戏，为您带来爽 快 的 自 由 砍 杀 体验',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 21,
                achievements: 18,
                avgTime: 5
            },
            {
                id:37,
                name: '巫师 3：狂猎',
                enName: 'The Witcher 3: Wild Hunt',
                covers: ['/witcher/witcher.jpg', '/witcher/1.jpg', '/witcher/2.jpg', '/witcher/3.jpg', '/witcher/4.jpg'],
                tag: ['奇幻', '成人', '剧情丰富','开放世界'],
                originalPrice: 127,
                nowPrice: 23,
                score:9.6,
                scoreNum: 36548,
                intro: '随着北方领域战乱四起，您接下了此生最为重大的一笔委托：找到预言之子，一件足以改变世界面貌的活生生的武器。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 21,
                achievements: 18,
                avgTime: 5
            },
            {
                id:38,
                name: '城市：天际线',
                enName: 'Cities: Skylines',
                covers: ['/cities/cities.jpg', '/cities/1.jpg', '/cities/2.jpg', '/cities/3.jpg', '/cities/4.jpg'],
                tag: ['资源管理', '模拟', '沙盒','城市建造'],
                originalPrice: 108,
                nowPrice: 27,
                score:9.4,
                scoreNum: 2256,
                intro: '《城市：天际线》是对经典城市模拟类游戏的现代演绎。该游戏引入了全新的游戏玩法元素，让玩家切身体会到创造和维持一座真正城市的兴奋和艰辛，同时扩展了城市建设体验中的一些经久不衰的主题。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 21,
                achievements: 18,
                avgTime: 5
            },
            {
                id:39,
                name: '欧洲卡车模拟2',
                enName: 'Euro Truck Simulator 2',
                covers: ['/oka/oka.jpg', '/oka/1.jpg', '/oka/2.jpg', '/oka/3.jpg', '/oka/4.jpg'],
                tag: ['资源管理', '模拟', '沙盒','城市建造'],
                originalPrice: 108,
                nowPrice: 21,
                score:9.6,
                scoreNum: 6228,
                intro: '《城市：天际线》是对经典城市模拟类游戏的现代演绎。该游戏引入了全新的游戏玩法元素，让玩家切身体会到创造和维持一座真正城市的兴奋和艰辛，同时扩展了城市建设体验中的一些经久不衰的主题。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 21,
                achievements: 18,
                avgTime: 5
            },
            {
                id:40,
                name: 'Warframe',
                enName: 'Warframe',
                covers: ['/img/1.jpg', '/oka/1.jpg', '/oka/2.jpg', '/oka/3.jpg', '/oka/4.jpg'],
                tag: ['免费开玩', '动作', '角色扮演','合作'],
                originalPrice: 1,
                nowPrice: 0,
                score:5.6,
                scoreNum: 6234,
                intro: '在这个以故事为导向的免费在线动作游戏中，觉醒为一个不可阻挡的战士，并与你的朋友一起战斗。跟随着神秘的 Lotus 的指引，在广阔的星系中直面敌对的派系，提升你的战甲等级，建立一个具有毁灭性火力的军械库；并在这个惊心动魄，且拥有独特第三人称战斗体验的庞大开放世界中发挥你的真',
                recommend: false,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:41,
                name: 'Assassin’s Creed® Odyssey',
                enName: 'Assassin’s Creed® Odyssey',
                covers: ['/img/2.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['暗杀', '动作', '角色扮演','冒险'],
                originalPrice: 298,
                nowPrice: 59,
                score:9.4,
                scoreNum: 15248,
                intro: '在《Assassin‘s Creed® Odyssey》当中主宰自己的命运。 从一名流浪者蜕变成传奇人物，踏上这趟奥德赛之旅，找出你过往的秘密并改变古希腊的命运。 Lotus 的指引，在广阔的星系中直面敌对的派系，提升你的战甲等级，建立一个具有毁灭性火力的军械库；并在这个惊心动魄，且拥有独特第三人称战斗体验的庞大开放世界中发挥你的真',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:42,
                name: '刺客信条 起源',
                enName: 'Assassin‘s Creed® Origins',
                covers: ['/img/3.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['暗杀', '动作', '角色扮演','冒险'],
                originalPrice: 298,
                nowPrice: 44.7,
                score:9.4,
                scoreNum: 15248,
                intro: '《ASSASSIN’S CREED® ORIGINS》是一次全新的开始 *《Assassin’s Creed》Discovery Tour现已免费更新！* 王权和阴谋统治下的古埃及时代正慢慢消失在争权夺位的冷酷之战中。重返刺客兄弟会起源的最初时刻，揭开不为人知的秘密和被遗忘的神秘事件。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:43,
                name: '战舰世界',
                enName: 'World of Warships',
                covers: ['/img/4.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:9.4,
                scoreNum: 25467,
                intro: '投身惊心动魄的海战，在超过400艘来自20世纪上半叶的战舰中组建您的舰队——从隐蔽的驱逐舰到巨型战列舰。变换您的战舰外观并选择适合您游戏风格的升级品，与其他玩家在战斗中并肩作战！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:44,
                name: '雀魂麻將',
                enName: 'MahjongSoul',
                covers: ['/img/5.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:9.4,
                scoreNum: 25467,
                intro: '随时随地，轻松麻将！ 精美和风立直麻将游戏——《雀魂麻将》国际中文服Steam版现已正式上线！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:45,
                name: 'Dota 2',
                enName: 'Dota 2',
                covers: ['/img/6.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:9.4,
                scoreNum: 25467,
                intro: '每一天全球有数百万玩家化为一百余名Dota英雄展开大战。不论是游戏时间刚满10小时还是1000小时，比赛中总能找到新鲜感。定期的更新则保证游戏性、功能和英雄都能持续发展，Dota 2已真正地焕发了生命。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:46,
                name: 'Brotato',
                enName: 'Brotato',
                covers: ['/img/7.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 22,
                nowPrice: 22,
                score:9.4,
                scoreNum: 25467,
                intro: '《Brotato》是一款自上而下的竞技场射击轻度ROGUE游戏，玩家将在游戏中扮演一个同时使用6种武器以击退成群外星人的土豆。从各种特征和道具中进行选择，创造独特的建筑并生存下去，直到救援到来。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:47,
                name: 'Fallout 4',
                enName: 'Fallout 4',
                covers: ['/img/8.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 56,
                nowPrice: 22,
                score:9.4,
                scoreNum: 25467,
                intro: 'Bethesda Game Studios, the award-winning creators of Fallout 3 and The Elder Scrolls V: Skyrim, welcome you to the world of Fallout 4 – their most ambitious game ever, and the next generation of open-world gaming.',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:48,
                name: '嗜血印',
                enName: 'Bloody Spell',
                covers: ['/img/13.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 79,
                nowPrice: 29,
                score:9.4,
                scoreNum: 54667,
                intro: '随时随地，轻松麻将！ 精美和风立直麻将游戏——《雀魂麻将》国际中文服Steam版现已正式上线！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:49,
                name: '小小梦魇2',
                enName: 'Little Nightmares II Demo',
                covers: ['/img/9.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 102,
                nowPrice: 56,
                score:9.4,
                scoreNum: 2546,
                intro: '在《小小梦魇2》的悬疑冒险旅途中，您将化身为小男孩摩诺，身处在电波笼罩之下，因此变得扭曲的世界里。 与新结交的朋友小六携手合作，揭发讯号塔暗藏的秘密',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:50,
                name: '喵斯快跑',
                enName: 'Muse Dash',
                covers: ['/img/10.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 18,
                nowPrice: 8,
                score:9.4,
                scoreNum: 2547,
                intro: '狂拽跑酷和传统音游结合的世界 ★★★ —— 《 Muse Dash 》!!',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:51,
                name: 'The Escapists 2',
                enName: 'The Escapists 2',
                covers: ['/img/11.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 23,
                nowPrice: 10,
                score:9.5,
                scoreNum: 19343,
                intro: '诡计、偷盗、打架以及逃脱！当你在《The Escapists 2》中回到当一名囚犯的生活时，现在也该通过多玩家模式从世界上最艰苦的监狱中逃脱出来了。你知道逃脱都需要什么吗？',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:52,
                name: '死或生：沙滩排球维纳斯假期',
                enName: 'DEAD OR ALIVE Xtreme Venus Vacation',
                covers: ['/img/12.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:7.3,
                scoreNum: 2547,
                intro: '光荣特库摩的『DEAD OR ALIVE Xtreme Venus Vacation』让玩家扮演「维纳斯群岛」的岛主，协助『DEAD OR ALIVE』系列的女孩们在美丽与强劲的祭典—「维纳斯挑战赛」中获胜，并与女孩们共谱美好回忆。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:53,
                name: '命运2',
                enName: 'Destiny 2: Lightfall',
                covers: ['/img/14.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:9.1,
                scoreNum: 25147,
                intro: '命运2是发生在一个独立进化的世界中的一款免费的大型多人线上动作游戏。你可以在任何时间与任何地点和你的朋友们进行游戏。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:54,
                name: '蝙蝠侠™：阿卡姆骑士',
                enName: 'Batman™: Arkham Knight',
                covers: ['/img/15.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 68,
                nowPrice: 13,
                score:9.4,
                scoreNum: 2547,
                intro: '《蝙蝠侠™：阿卡姆骑士》将 Rocksteady Studios 获奖的“阿卡姆”三部曲带入史诗般的结局。《蝙蝠侠：阿卡姆骑士》新世代平台独占游戏，将有 Rocksteady 专门设计的蝙蝠车。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:55,
                name: '剑士',
                enName: 'Kenshi',
                covers: ['/img/55.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 90,
                nowPrice: 45,
                score:9.4,
                scoreNum: 2547,
                intro: '一款以自由行动小分队为基础的角色扮演RPG类游戏。专注于开放式的沙盒游戏功能而非线性故事。选择成为商人、小偷、反叛者、军阀、冒险者、农民、奴隶或是食人族的牙祭。探索新设备，锻造新装备',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:56,
                name: 'Inside the Backrooms',
                enName: ' Inside the Backrooms',
                covers: ['/img/56.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 22,
                nowPrice: 22,
                score:9.4,
                scoreNum: 2547,
                intro: 'Inside the Backrooms is a horror multiplayer game mixed with different mechanics that will make you spend an intense night with friends. Explore, think, interact, but be careful, it is rumored that there are several entities wishing to find you...',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:57,
                name: '奇怪的RPG',
                enName: '奇怪的RPG',
                covers: ['/img/57.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 38,
                nowPrice: 32,
                score:9.4,
                scoreNum: 2547,
                intro: '侧重Boss战的高难度、快节奏动作ARPG游戏。玩家身为已死之人被召到乐园，踏上了拯救灾难的无限世界之旅，而乐园的秘密也随之浮现......',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:58,
                name: '鹅作剧',
                enName: 'Untitled Goose Game',
                covers: ['/img/58.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 70,
                nowPrice: 35,
                score:9.9,
                scoreNum: 1547,
                intro: '今天村里天气真不错，而你是一只可怕的鹅。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:59,
                name: '茶杯头',
                enName: 'Cuphead',
                covers: ['/img/59.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 68,
                nowPrice: 47,
                score:9.2,
                scoreNum: 3247,
                intro: '《茶杯头》是一款以BOSS对战为主的经典横版卷轴类射击游戏。受上世纪30年代动画片的启发，游戏无论是画面还是音效都努力再现了当时的技术，如传统的赛璐璐手绘动画、水彩背景还有原声爵士乐录音等。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:60,
                name: '穹顶守护者',
                enName: 'Dome Keeper  ',
                covers: ['/img/60.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 88,
                nowPrice: 40,
                score:9.0,
                scoreNum: 1847,
                intro: '在这款创新的 roguelike 采矿动作游戏中，抵御一波又一波的外星攻击者，挖掘资源并选择强大的升级路径吧。你是否有足够时间再挖深一点，然后赶在怪物攻击穹顶之前回去防守呢？',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:61,
                name: '狙击手：幽灵战士契约 2',
                enName: 'Sniper Ghost Warrior Contracts 2 ',
                covers: ['/img/61.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 70,
                nowPrice: 35,
                score:9.9,
                scoreNum: 1547,
                intro: '《狙击手幽灵战士契约2》的背景在中东，是一款现代战争战术类射击游戏。在游戏中，玩家扮演代号渡鸦的契约狙击手刺客，在激动人心的单人战役中消灭一连串目标。你将在超过1000米的超远距离外狙杀目标，准备好体验系列中最刺激人心的一作吧。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:62,
                name: '战术小队',
                enName: 'Squad ',
                covers: ['/img/62.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 149,
                nowPrice: 149,
                score:8.9,
                scoreNum: 85435,
                intro: '战术小队是一款通过战术交流与配合来描绘真实战场体验的50vs50在线多人第一人称射击类游戏。主要内容包括基于载具的联合作战游戏体验、大规模战场、前线基地建造以及专为区域语音交流和无线电所打造的语音通讯系统',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:63,
                name: '太吾绘卷 ',
                enName: 'The Scroll Of Taiwu ',
                covers: ['/img/63.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 68,
                nowPrice: 35,
                score:8.3,
                scoreNum: 41547,
                intro: '《太吾绘卷》是一款以神话和武侠为题材的独立游戏。玩家将扮演神秘的“太吾氏传人”，在以古代中华神州为背景的架空世界中，通过一代又一代传人的努力和牺牲，最终击败强大的宿敌，决定人世的命运。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:64,
                name: '死亡空间',
                enName: 'Dead Space ',
                covers: ['/img/64.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 248,
                nowPrice: 228,
                score:9.0,
                scoreNum: 1547,
                intro: '科幻生存恐怖经典作品宣告回归，完全重建，旨在为玩家提供更身临其境的体验，包括视觉、音效和游戏性改进，同时尽力忠实地还原初版游戏惊险的视觉效果。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:65,
                name: '地球不屈',
                enName: 'Terra Invicta ',
                covers: ['/img/65.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 70,
                nowPrice: 35,
                score:9.4,
                scoreNum: 1347,
                intro: '神秘的外星力量逼近太阳系，不知是敌是友。关于外星人的动机和应对方法，众说纷纭。你将参与各方力量的角逐，率领你的派系，在太阳系中实现你的愿景。《地球不屈》是宏大的硬科幻战略游戏： 战斗符合牛顿物理学；太阳系的比例高度准确；允许自定义飞船设计；战略情况因为公转而充满复杂',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:66,
                name: 'Lost2',
                enName: 'Lost2 ',
                covers: ['/img/66.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 36,
                nowPrice: 32,
                score:9.4,
                scoreNum: 1547,
                intro: '這是一款黑暗童話題材的點擊解密遊戲。玩家需要穿梭在數十個有關童話的黑暗夢境中，通過觀察場景並使用道具互動，來幫助童話故事裡久負盛名的公主和其他角色擺脫困境。當然，有的時候你也需要再製造一點小小的麻煩，來滿足自己邪惡的慾望，於她們展開一場甜美而黑暗的互動。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:67,
                name: '虚空穹牢',
                enName: 'Vault of the Void ',
                covers: ['/img/67.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 62,
                nowPrice: 35,
                score:8.1,
                scoreNum: 1547,
                intro: '这是一款结合了Roguelite元素的CCG卡牌收集游戏。随着游戏进展，使用更多卡牌来构建更强的牌组。用虚空石升级并自定义你的卡牌，为其注入新的力量，以助你击败虚空及其爪牙。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:68,
                name: '边缘世界',
                enName: 'RimWorld ',
                covers: ['/img/68.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 103,
                nowPrice: 50,
                score:8.5,
                scoreNum: 15147,
                intro: '由聪明的人工智能故事讲述者驱动的科幻殖民地模拟电脑游戏。通过模拟心理学、生态学、枪战、近战、气候、生物群落、外交、人际关系、艺术、医学、贸易等来生成故事。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:69,
                name: '噬血代码',
                enName: 'CODE VEIN ',
                covers: ['/img/69.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 368,
                nowPrice: 55,
                score:8.2,
                scoreNum: 1547,
                intro: '时间在近未来，因为“审判荆棘”的出现，世界步向毁灭，名为“VEIN”的封闭土地相应而生',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:70,
                name: 'Action对魔忍',
                enName: 'Action对魔忍 ',
                covers: ['/img/70.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:7.8,
                scoreNum: 1547,
                intro: '统率超人忍者们对抗邪恶势力！对魔忍系列角色展开的近未来忍者动作RPG！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:71,
                name: 'Raft',
                enName: 'Raft ',
                covers: ['/img/71.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 68,
                nowPrice: 68,
                score:7.8,
                scoreNum: 1547,
                intro: 'Raft throws you and your friends into an epic oceanic adventure! Alone or together, players battle to survive a perilous voyage across a vast sea! Gather debris, scavenge reefs and build your own floating home, but be wary of the man-eating sharks!',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:72,
                name: '战锤：末世鼠疫2',
                enName: 'Warhammer: Vermintide 2 ',
                covers: ['/img/72.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 110,
                nowPrice: 22,
                score:8.8,
                scoreNum: 15547,
                intro: '这款精彩的近战动作游戏是广受赞誉的 Vermintide 的续作，将用视觉上的冲击为第一人称合作游戏带来崭新的定义。现在就加入战斗吧！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:73,
                name: '足球经理',
                enName: 'Football Manager 2023 ',
                covers: ['/img/73.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 268,
                nowPrice: 214,
                score:9.2,
                scoreNum: 11547,
                intro: '《足球经理（Football Manager）2023》的新功能让您能更接近这款精美游戏的各个层面。准备好来趟的足球荣耀之旅吧。 预购可享 20% 折扣并抢先体验*。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:74,
                name: '群星',
                enName: 'Stellaris ',
                covers: ['/img/74.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 148,
                nowPrice: 148,
                score:9.8,
                scoreNum: 15947,
                intro: '在这款由Paradox Development Studio精心打造的科幻大型战略游戏中，探索充满奇迹的浩瀚银河。与千奇百怪的外星种族互动、发现奇异新世界并体验其中令人意想不到的事件，同时扩大您帝国的影响力。每一场新的冒险皆拥有几乎无穷无尽的可能性。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:75,
                name: '维多利亚3',
                enName: 'Victoria 3 ',
                covers: ['/img/75.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 218,
                nowPrice: 111,
                score:8.6,
                scoreNum: 3247,
                intro: 'Paradox Development Studio 邀请您到精彩刺激且充满变革的 19 世纪打造理想的社会。在 Paradox 史上最受期待的游戏之一《Victoria 3》中，平衡社会上存在的利益冲突，并称霸天下。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:76,
                name: 'Assassin’s Creed® IV Black Flag™',
                enName: 'Assassin’s Creed® IV Black Flag™ ',
                covers: ['/img/76.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 190,
                nowPrice: 59,
                score:8.6,
                scoreNum: 15647,
                intro: 'The year is 1715. Pirates rule the Caribbean and have established their own lawless Republic where corruption, greediness and cruelty are commonplace.Among these outlaws is a brash young captain named Edward Kenway.',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:77,
                name: '了不起的修仙模拟器',
                enName: '了不起的修仙模拟器 1.0 ',
                covers: ['/img/77.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 88,
                nowPrice: 61,
                score:8.9,
                scoreNum: 15947,
                intro: '独一无二的修仙游戏，建立属于你的仙门，招收天资绝代的弟子，建造美轮美奂的建筑，收集各种神妙的修行功法、灵药法宝、神通秘籍。搭建修行宝地，让门下弟子逐步修行突破。筑基、炼气、结丹、元神等境界，最终度过天劫飞升成仙。将你的门派从一无所有的乡村聚落，经营成威名赫赫的高',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:78,
                name: '骑马与砍杀2：霸主 ',
                enName: 'Action对魔忍 ',
                covers: ['/img/78.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 248,
                nowPrice: 248,
                score:8.8,
                scoreNum: 154627,
                intro: '号角震天，群鸦蔽日。卡拉德帝国因内乱而陷入三分之境。新的王国正在悄然崛起。佩好长剑，缚紧盔甲，招兵买马，在卡拉迪亚大陆的战场上策马驰骋，赢取荣耀。荡尽旧世界的灰烬，创造属于你的新世界，建立雄踞一方的新霸权，成为卡拉迪亚的霸主吧！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:79,
                name: '不义联盟 2',
                enName: 'Injustice™ 2 ',
                covers: ['/img/79.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 138,
                nowPrice: 13.8,
                score:8.4,
                scoreNum: 1547,
                intro: '在《不义联盟 2》中建构以及增强你最喜欢的 DC 传奇终极版本。这是你的传奇、你的征程，你的不义联盟。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:80,
                name: '辐射76：匹兹堡',
                enName: 'Fallout 76: The Pitt ',
                covers: ['/img/80.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 165,
                nowPrice: 41.25,
                score:7.8,
                scoreNum: 1547,
                intro: 'Bethesda Game Studios邀您进入《Fallout 76》的世界。在核弹爆炸的25年后，你和其他避难所居民进入了核爆之后的美国。加入《Fallout》系列故事选新推出的开放世界多人游戏，探索核战争留下的广阔废土。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:81,
                name: '星露谷物语',
                enName: 'Stardew Valley ',
                covers: ['/img/81.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 48,
                nowPrice: 48,
                score:9.8,
                scoreNum: 1947,
                intro: '你继承了你爷爷在星露谷留下的老旧农场。带着爷爷留下的残旧工具和几枚硬币开始了你的新生活。你能适应这小镇上的生活并且将这个杂草丛生的老旧农场变成一个繁荣的家吗？',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:82,
                name: '乱揍派对”',
                enName: 'Pummel Party ',
                covers: ['/img/82.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 50,
                nowPrice: 50,
                score:8.6,
                scoreNum: 5547,
                intro: '《Pummel Party》是一款支持 4-8 位玩家的在线和本地多人派对游戏。Pummel 好友或 AI 可以在图板模式下使用各种各样荒唐爆笑的物品，在独特的迷你游戏合集中相互竞争，摧毁友谊。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:83,
                name: '最远的边陲',
                enName: 'Farthest Frontier ',
                covers: ['/img/83.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 90,
                nowPrice: 46,
                score:8.8,
                scoreNum: 16452,
                intro: '保护并领导你的村民在已知世界的边缘地带，从原始的荒野中打造出一个城镇。通过收集原材料、狩猎、捕鱼和耕种来维持生存。制造物品来进行交易、消费、装备和战斗，并在与自然和外部威胁的对抗中生存下来。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:84,
                name: '钢铁之尾',
                enName: 'Tails of Iron ',
                covers: ['/img/84.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 99,
                nowPrice: 39.6,
                score:7.4,
                scoreNum: 2568,
                intro: '《Tails of Iron》是一款充斥着残酷战斗的史诗RPG冒险游戏。作为玩家的你将扮演鼠国的王位继承人雷唧，并踏上一段光复王国的险象环生之旅。探索婀娜多姿却又危机四伏的世界。招募一众英勇同伴。披荆斩棘…彻底终结残忍的蛙族！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:85,
                name: '严阵以待',
                enName: 'Ready or Not ',
                covers: ['/img/85.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 125,
                nowPrice: 125,
                score:8.8,
                scoreNum: 29864,
                intro: '《严阵以待》是一款激烈的战术型第一人称射击游戏，描绘现代世界中特警组警员奉命展开行动，前往解决各种危险艰难情况的过程',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:86,
                name: '只狼：影逝二度',
                enName: 'Sekiro™: Shadows Die Twice - GOTY Edition ',
                covers: ['/img/86.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 268,
                nowPrice: 268,
                score:9.5,
                scoreNum: 11547,
                intro: '进入由打造了《黑暗之魂》系列的知名开发商FromSoftware倾力制作的全新冒险，用智慧和力量斩开复仇之路。 决死复仇，夺回荣誉，智杀强敌',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:87,
                name: '枪火重生',
                enName: 'Gunfire Reborn ',
                covers: ['/img/87.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 68,
                nowPrice: 29,
                score:7.9,
                scoreNum: 2651,
                intro: '《枪火重生》是一款融合了第一人称射击、Roguelite随机要素和RPG策略选择的冒险闯关游戏。玩家在游戏里可以操纵不同能力的英雄组建多种Build玩法，使用随机掉落的武器在随机性关卡中进行冒险挑战。可以单人畅玩，也可以最多四人组队挑战。                ',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:88,
                name: '灵境奇谈',
                enName: ' 灵境奇谈 ',
                covers: ['/img/88.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:8.8,
                scoreNum: 3337,
                intro: '灵境奇谈是由GKD Game Studio推出的一款写实东方文化，1V5非对称竞技游戏。游戏基于包罗万象的东方传统文化而设计，将五行八卦、民间风俗和大量东方特有的文化元素融入其中，以此让玩家切身体验东方传统志怪文化的魅力所在。你将扮演灵调局探员，展开沉浸式的探险。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:89,
                name: '融雪',
                enName: '融雪 ',
                covers: ['/img/89.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 36,
                nowPrice: 30,
                score:7.2,
                scoreNum: 3210,
                intro: '平安夜，一年中最重要的一天，我卻失去了一切。失魂落魄的我獨自坐在公園的長椅上，就在此時一個女孩子出現在我的面前「那個……你現在有空嗎？你要是不說話，我就當有空了！」在她的帶領下，我來到了這家名為「融雪」的酒吧……於是，發生在冬季的溫馨愛情故事，就這麼開始了。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:90,
                name: '僵尸毁灭工程',
                enName: 'Project Zomboid ',
                covers: ['/img/90.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 70,
                nowPrice: 70,
                score:6.2,
                scoreNum: 147,
                intro: ' 僵尸计划是僵尸生存的终极。单独或在MP中：你在生存的斗争中掠夺，建造，制作，战斗，耕种和捕鱼。一个硬核RPG技能集，一个巨大的地图，大规模可定制的沙盒和一个可爱的教程浣熊等待着不小心。那么你将如何死去呢？所有需要是一口。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:91,
                name: '暴君的游戏',
                enName: 'Despot’s Game ',
                covers: ['/img/91.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 79,
                nowPrice: 71.1,
                score:7.7,
                scoreNum: 2547,
                intro: '《暴君的游戏》（Despot’s Game）是一款带来涡轮增压式战斗的 roguelike 策略游戏。组建队伍，牺牲到底，击溃敌军……以及其他玩家！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:92,
                name: '帝国时代 IV',
                enName: 'Age of Empires IV ',
                covers: ['/img/92.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 199,
                nowPrice: 165,
                score:6.9,
                scoreNum: 15147,
                intro: '最受欢迎的即时战略游戏之一将随《帝国时代 IV》荣耀回归，让您置身于塑造现代世界的史诗般历史战役的中心。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:93,
                name: '装机模拟器',
                enName: 'PC Building Simulator ',
                covers: ['/img/93.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 70,
                nowPrice: 21,
                score:8.8,
                scoreNum: 11547,
                intro: '建立并发展属于自己的电脑维修企业，学习诊断、修理和装配电脑。有了真实世界的授权配件以及全面的硬软件模拟，你就可以规划并装配出自己的终极电脑。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:94,
                name: '流浪',
                enName: 'Stray ',
                covers: ['/img/94.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 95,
                nowPrice: 90,
                score:9.8,
                scoreNum: 12547,
                intro: '一只孤身离群的流浪猫迷失在了一座被遗忘的网络城市里，它必须解开一个古老的谜团才能逃离出去，找到回家的路。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 100,
                achievements: 18,
                avgTime: 5
            },
            {
                id:95,
                name: 'SCUM',
                enName: 'SCUM ',
                covers: ['/img/95.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 129,
                nowPrice: 129,
                score:6.8,
                scoreNum: 6547,
                intro: '娱乐巨头TEC1公司推出的惊世大作《SCUM》第二季，点燃了全球观众心中嗜血的欲望。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:96,
                name: '光明记忆：无限',
                enName: 'Bright Memory: Infinite',
                covers: ['/img/96.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 48,
                nowPrice: 20,
                score:7.1,
                scoreNum: 15947,
                intro: '《光明记忆：无限》国内游戏开发者"飞燕群岛"最新作品。2036年世界各地的天空上突然出现了异象，一个巨型的黑洞出现天空中吞噬着山脉和古建筑，科学家们无法解释这些现象，事件背后牵连着世界的存亡。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:97,
                name: '胡闹厨房 全都好吃',
                enName: 'Overcooked! ',
                covers: ['/img/97.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 130,
                nowPrice: 100,
                score:8.8,
                scoreNum: 18547,
                intro: '在拥有 4K 画质并以 60 FPS 顺畅运行的《Overcooked! 1》和《Overcooked! 2》中，尽情体验洋葱王国的一切。彻底重制、重新烹调。享受超过 200 个关卡 (7 个全新关卡) 和 80 位以上的大厨 (3 位全新大厨)，这是终极的《Overcooked!》游戏体验。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:98,
                name: '七日杀',
                enName: '7 Days to Die ',
                covers: ['/img/98.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 78,
                nowPrice: 78,
                score:7.8,
                scoreNum: 6547,
                intro: '《7 Days》是一款开放世界游戏，独具特色地融合了第一人称射击、生存恐怖、塔防和角色扮演等多种游戏的特征。快来体验这款具有开创性的终极丧尸生存沙盒角色扮演游戏吧。纳维戈恩在等着你！',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:99,
                name: '三国杀',
                enName: 'Action对魔忍 ',
                covers: ['/img/99.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 1,
                nowPrice: 0,
                score:5.8,
                scoreNum: 185547,
                intro: '《三国杀》是一款拥有沉浸体验感的以三国时代为背景的线上卡牌游戏。玩家可扮演三国时期人物，根据随机抽中的隐藏身份（主公、反贼、忠臣、内奸），通过使用独特的人物技能，合理打出各种类型的手牌，运筹帷幄、智取搏杀，获得自己所属身份的胜利！ 《三国杀》将三国历史与桌面游戏结',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
            {
                id:100,
                name: '深岩银河',
                enName: 'Deep Rock Galactic ',
                covers: ['/img/100.jpg', '/1.jpg', '/2.jpg', '/3.jpg', '/4.jpg'],
                tag: ['海战', '军事', '免费开完','冒险'],
                originalPrice: 90,
                nowPrice: 60,
                score:7.8,
                scoreNum: 1547,
                intro: '《深岩银河》是一款多人合作类第一人称射击游戏，有着了不起的矮人、100% 可破坏的地形、由程序生成的洞穴以及无数的外星怪物。',
                recommend: true,
                recomReason: 'Steam促销',
                salesVolume: 22,
                achievements: 18,
                avgTime: 5
            },
        ],

        //更多游戏
        moreGame: {
            title: '为您推荐',
            games: []
        },

        //所有用户信息
        users: [
            {
                id: 1,
                account: '123',
                password: '123',
                name: 'Dyz',
                level: '19',
                signature: '这是个性签名',
                avatar: '/head2.jpg',
                fans: [2, 3, 4, 5, 6, 7],
                atten: [2, 3, 4, 5, 6, 7],
                praise: 0,
                browse: 9,
                ownGames: [
                    {
                        id: 4,
                        totalTime: 160.2,
                        recentTime: 0,
                        myAchievements: 22,
                        other: {}
                    },
                    {
                        id: 5,
                        totalTime: 45.8,
                        recentTime: 12,
                        myAchievements: 56,
                        other: {}
                    },
                    {
                        id: 10,
                        totalTime: 90,
                        recentTime: 24,
                        myAchievements: 32,
                        other: {}
                    },
                    {
                        id: 8,
                        totalTime: 122.1,
                        recentTime: 3.5,
                        myAchievements: 24,
                        other: {}
                    },
                ]
            },
            {
                id: 2,
                account: '1111',
                password: '1111',
                name: '用户2',
                level: '16',
                signature: '这是用户2的个性签名',
                avatar: '/head.jpg',
                fans: [2, 3],
                atten: [2, 3, 4, 5],
                praise: 0,
                browse: 10,
                ownGames: [
                    {
                        id: 2,
                        totalTime: 66,
                        recentTime: 3,
                        myAchievements: 10,
                        other: {}
                    },
                    {
                        id: 6,
                        totalTime: 79,
                        recentTime: 3.5,
                        myAchievements: 10,
                        other: {}
                    },
                ]
            },
        ],

        //当前登录用户信息
        userInfo: null,

        //首页数据
        articleList: [
            {
                id: 1,
                cover: '/index/comment1.jpg',
                title: '【GTA改装车】ZR350改装案例分享',
                tag: '侠盗猎车手5',
                commentsNum: 123,
                author: {
                    name: '星游鉴赏社',
                    time: '12分钟前',
                    avatar: '/head/1.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 2,
                cover: '/index/comment2.jpg',
                title: '【NS好价游戏】新"肝"王驾到？一个动物园，造了一晚上！3超肝游戏推荐！',
                tag: 'Switch',
                commentsNum: 10,
                author: {
                    name: '游戏资讯BOT',
                    time: '21分钟前',
                    avatar: '/head/2.jpg'
                },
                text: '截至目前为止，网络上已经泄露了多段《暗黑破坏神4》过场动画和动捕视频，其中显示游戏将包含两种教程选择。今日，俄罗斯黑客组织Blizzless再次泄露了一批的截图，其中包括游戏的捏脸、选角、技能树等内容界面，该组织曾多次黑入暴雪内部，泄露过《魔兽争霸3》、《暗黑破坏神2》等内容。\n' +
                    '      暗黑破坏神4》是一款动作角色扮演游戏，游戏开放世界中包含150个地下城，清除敌对区域后可以成为友善城镇。还有挑战世界Boss等玩法，可以和其他玩家合作挑战，同时还有专属的PVP区域，支持跨平台联机。游戏保持了系列游戏的高质量高水准，有多种职业可以选择，每种职业都有自己独特的技能和玩法，让玩家百玩不厌。\n' +
                    '      《暗黑破坏神4》封闭测试现已开放邀请，本作计划于 2023 年发布，公测将于明年初开启敬请期待。'
            },
            {
                id: 3,
                cover: '/index/comment3.jpg',
                title: '泰拉瑞亚最新的11个成就攻略',
                tag: 'PC游戏',
                commentsNum: 15,
                author: {
                    name: '芜湖金牌飞行员',
                    time: '34分钟前',
                    avatar: '/head/3.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 4,
                cover: '/index/comment4.jpg',
                title: '黑盒晚报：《动物派对》开发接近尾声；外网爆料《死亡搁浅2开发中》',
                tag: 'PC游戏',
                commentsNum: 155,
                author: {
                    name: '游戏资讯BOT',
                    time: '33分钟前',
                    avatar: '/head/4.jpg'
                },
                text: '截至目前为止，网络上已经泄露了多段《暗黑破坏神4》过场动画和动捕视频，其中显示游戏将包含两种教程选择。今日，俄罗斯黑客组织Blizzless再次泄露了一批的截图，其中包括游戏的捏脸、选角、技能树等内容界面，该组织曾多次黑入暴雪内部，泄露过《魔兽争霸3》、《暗黑破坏神2》等内容。\n' +
                    '      暗黑破坏神4》是一款动作角色扮演游戏，游戏开放世界中包含150个地下城，清除敌对区域后可以成为友善城镇。还有挑战世界Boss等玩法，可以和其他玩家合作挑战，同时还有专属的PVP区域，支持跨平台联机。游戏保持了系列游戏的高质量高水准，有多种职业可以选择，每种职业都有自己独特的技能和玩法，让玩家百玩不厌。\n' +
                    '      《暗黑破坏神4》封闭测试现已开放邀请，本作计划于 2023 年发布，公测将于明年初开启敬请期待。'
            },
            {
                id: 5,
                cover: '/index/comment5.jpg',
                title: '废土快递————尚可一玩的经营游戏',
                tag: 'PC游戏',
                commentsNum: 33,
                author: {
                    name: '暴走秋田郡',
                    time: '55分钟前',
                    avatar: '/head/5.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 6,
                cover: '/index/comment6.jpg',
                title: '恐怖解谜游戏《蔑视》8分钟实机展示 收发XGP',
                tag: 'PC游戏',
                commentsNum: 80,
                author: {
                    name: '-PHONEnix-',
                    time: '1小时前',
                    avatar: '/head/6.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 7,
                cover: '/index/comment7.jpg',
                title: '特斯拉2022年AI日活动开启：人形机器人擎天柱现身',
                tag: '盒友杂谈',
                commentsNum: 109,
                author: {
                    name: 'TD黄瓜',
                    time: '1小时前',
                    avatar: '/head/1.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 8,
                cover: '/index/comment8.jpg',
                title: '【每周欢乐】Epic喜加二，亚马逊将送全战2，GOG喜加一，Steam喜加一堆',
                tag: 'PC游戏',
                commentsNum: 104,
                author: {
                    name: 'dtsad',
                    time: '2小时前',
                    avatar: '/head/2.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 9,
                cover: '/index/comment10.jpg',
                title: '乐高Ideas作品塞尔达传说时之圣殿获得万票支持~成功入审',
                tag: '盒友杂谈',
                commentsNum: 43,
                author: {
                    name: '任地狱',
                    time: '2小时前',
                    avatar: '/head/4.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 10,
                cover: '/index/comment9.jpg',
                title: '【个人向解析《边缘行者》】什么也带不来，什么也带不走！',
                tag: '盒友杂谈',
                commentsNum: 98,
                author: {
                    name: '游戏资讯BOT',
                    time: '3小时前',
                    avatar: '/head/6.jpg'
                },
                text: '《骑马与砍杀 II : 领主》即将于10月25日发售，今日官方于steam发布公告。\n' +
                    '随着发布日期的临近，官方表示正在准备许多其他更新。首先官方展示了旗帜的外观游戏中的旗帜将是玩家和AI英雄领导的阵型的可装备物品。' +
                    '除此以外，游戏还将推出带有布料附件的新工艺品。不仅允许玩家创造具有额外天赋的武器，还将增加整体视觉体验，部队也可以携带它们。此外，官方表示一直在努力开发新的场景。' +
                    '53个城镇中的每一个都将是独一无二的，城堡、战斗地形和藏身处等也将继续扩大。当然，世界地图也将得到进一步的改进。\n' +
                    '同时官方正在完成AI移动系统的基本改造，这有助于NPC应对困难地形（如围城），并显著改善拥堵问题。它通过一系列物理调整、更好的情境理解等来实现这一点。' +
                    '当你的角色变得太老太累而无法继续战斗，你可以将权力交给继任者或者结束氏族。这会带来一定的仪式感。游戏内的过场动画会展示这个过程。届时你可以回顾这些年来你所取得的成就。' +
                    '这就是游戏结束统计数据的用武之地——跟踪你的每一步（或至少其中一些），并在你的游戏结束或完成故事情节时提供数据。'
            },
            {
                id: 11,
                cover: '/index/comment11.jpg',
                title: 'PS4游戏推荐（个人向）',
                tag: '主机游戏',
                commentsNum: 80,
                author: {
                    name: 'sajhd',
                    time: '3小时前',
                    avatar: '/head/5.jpg'
                },
                text: '截至目前为止，网络上已经泄露了多段《暗黑破坏神4》过场动画和动捕视频，其中显示游戏将包含两种教程选择。今日，俄罗斯黑客组织Blizzless再次泄露了一批的截图，其中包括游戏的捏脸、选角、技能树等内容界面，该组织曾多次黑入暴雪内部，泄露过《魔兽争霸3》、《暗黑破坏神2》等内容。\n' +
                    '      暗黑破坏神4》是一款动作角色扮演游戏，游戏开放世界中包含150个地下城，清除敌对区域后可以成为友善城镇。还有挑战世界Boss等玩法，可以和其他玩家合作挑战，同时还有专属的PVP区域，支持跨平台联机。游戏保持了系列游戏的高质量高水准，有多种职业可以选择，每种职业都有自己独特的技能和玩法，让玩家百玩不厌。\n' +
                    '      《暗黑破坏神4》封闭测试现已开放邀请，本作计划于 2023 年发布，公测将于明年初开启敬请期待。'
            },
        ]
    },
    mutations: {
        //购买游戏后向用户所拥有的游戏列表追加一条游戏信息
        addGame(state, val) {
            state.userInfo.ownGames.push(val)
        },
        //设置当前登录的用户信息
        setUserInfo(state, val) {
            state.userInfo = val
        },
        //设置更多游戏列表
        setMoreGame(state, val) {
            state.moreGame = {
                title: val.title,
                games: val.games
            }
        }
    }
})
